### ISSUE TITLE
Crash with ArgumentOutOfRangeException.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/AvaloniaVS#112]
Repro:

1. Open Avalonia XAML editor
2. In body of `UserControl` type `<StackPanel`
3. Delete line (Ctrl+Shift+L)
4. Exception thrown:

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.
Parameter name: position
  Source=Microsoft.VisualStudio.Text.Data
  StackTrace:
   at Microsoft.VisualStudio.Text.SnapshotPoint..ctor(ITextSnapshot snapshot, Int32 position)
   at Microsoft.VisualStudio.Text.SnapshotPoint.op_Addition(SnapshotPoint point, Int32 offset)
   at AvaloniaVS.IntelliSense.XamlErrorTagger.GetTags(NormalizedSnapshotSpanCollection spans) in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\IntelliSense\XamlErrorTagger.cs:line 84
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext()
```

**Comment by grokys** [comment]
A similar thing happens if there's an error on the last line of the file and the last line is deleted.
