### ISSUE TITLE
'Exception has been thrown by the target of an invocation' in XAML Viewer

### ISSUE THREAD

**Issue by alexeybut** [AvaloniaUI/AvaloniaVS#154]
Very often I see 'Invalid Markup' on Previewer panel, but 'No issues found' on XAML text panel.
At the same time 'Exception has been thrown by the target of an invocation' on VS Error List, sometimes not. XML may be very simple with 1 control.
But code is compilable and works right in runtime. 
On Output Avalonia Diagnostics I can see
```
23:16:44.120 [Information] 920 Connection initialized
23:16:45.793 [Error] 920 UpdateXamlResult error
System.Xaml.XamlException: Exception has been thrown by the target of an invocation.
23:16:45.806 [Error] 920 UpdateXamlResult error
System.Xaml.XamlException: Exception has been thrown by the target of an invocation.
```

Microsoft Visual Studio Community 2019 Version 16.6.0
Windows 10 x64
AvaloniaUI 0.9.10 from nuget
Avalonia VS Extension 0.9.10 from VS marketplace

**Comment by alexeybut** [comment]
UPD: Sometimes I get
```
23:41:10.460 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433<---

23:41:10.511 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433<---
```

**Comment by alexeybut** [comment]
Sometimes
```
23:46:55.835 [Error] 17364 UpdateXamlResult error
System.Xaml.XamlException: Ambiguous match found.
23:46:55.840 [Error] 17364 UpdateXamlResult error
System.Xaml.XamlException: Ambiguous match found.
```

**Comment by dmrayt** [comment]
Since 0.9.10 i also always got the following exception.

```
10:16:08.746 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433<---
```

The problem is that in ``PreviewerProcess.cs:line 433`` the error object is null because no error has been set in UpdateXamlResultMessage (called from``RemoteDesignerEntryPoint.cs:line 204``)
