### ISSUE TITLE
The preview process  exited unexpectedly

### ISSUE THREAD

**Issue by microhobby** [AvaloniaUI/AvaloniaVS#155]
I'm getting the follow error on output when I try to open a design view:

```
19:44:13.616 [Information]  Avalonia Package initialized
19:45:44.214 [Error]  No executable found
19:45:51.431 [Information] 0 Stopping previewer process
19:45:54.585 [Information] 0 Starting previewer process for '"C:\Users\mpro3\Documents\work\dtn\avalon\TorizonAvaloniaSample\TorizonAvaloniaSample\bin\Debug\netcoreapp2.1\TorizonAvaloniaSample.dll"'
19:45:54.592 [Information] 20444 Started previewer process for '"C:\Users\mpro3\Documents\work\dtn\avalon\TorizonAvaloniaSample\TorizonAvaloniaSample\bin\Debug\netcoreapp2.1\TorizonAvaloniaSample.dll"'. Waiting for connection to be initialized.
19:45:55.146 [Information] 20444 Connection initialized
19:45:56.322 [Error] 20444 <= "Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object."
19:45:56.343 [Error] 20444 <= "   at TorizonAvaloniaSample.App.OnFrameworkInitializationCompleted() in C:\Users\mpro3\Documents\work\dtn\avalon\TorizonAvaloniaSample\TorizonAvaloniaSample\App.xaml.cs:line 29"
19:45:56.346 [Error] 20444 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.AppInitializer`1.GetConfiguredApp(IAvaloniaRemoteTransportConnection transport, CommandLineArgs args, Object obj) in C:\Users\mpro3\Documents\tmp\dn\Avalonia\src\Avalonia.DesignerSupport\Remote\RemoteDesignerEntryPoint.cs:line 120"
19:45:56.349 [Error] 20444 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in C:\Users\mpro3\Documents\tmp\dn\Avalonia\src\Avalonia.DesignerSupport\Remote\RemoteDesignerEntryPoint.cs:line 143"
19:45:56.351 [Error] 20444 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args)"
19:45:59.293 [Information]  Process exited
19:45:59.294 [Information]  Stopping previewer process
19:45:59.292 [Error]  Connection error
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<ReadExact>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.<Reader>d__16.MoveNext()
```

Microsoft Visual Studio Community 2019
Microsoft Visual Studio Community 2017 (I installed 2017 to see if I would have another result)
Windows 10 x64
AvaloniaUI 0.9.10 from nuget
Avalonia VS Extension 0.9.10 from VS marketplace

**Comment by microhobby** [comment]
The preview was broke because of some customizations I was making on App.xaml.cs

**Comment by microhobby** [comment]
@Gao996 I do not remember very clear the root cause, but it was my fault on the `App.xaml.cs`

**Comment by Gao996** [comment]
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly

**Comment by Gao996** [comment]
16:53:39.344 [Error] 19024 <= "   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)"
16:53:39.344 [Error] 19024 <= "   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)"
16:53:39.344 [Error] 19024 <= "   at System.Reflection.Assembly.LoadFile(String path)"
16:53:39.345 [Error] 19024 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 167"
16:53:39.345 [Error] 19024 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"

**Comment by 29654761** [comment]
I solved this problem via remove .vs folder and rebuild all solution.
It caused by I tried to upgrade avalonia base libraries.
