### ISSUE TITLE
Extension not load in VS 2019 [Version 16.11.6]

### ISSUE THREAD

**Issue by DmitryNizhebovsky** [AvaloniaUI/AvaloniaVS#224]
In VS ActivityLog.xml i found next message:

```
SetSite failed for package [AvaloniaPackage]Source: 'Microsoft.VisualStudio.Composition' Description: Expected 1 export(s) with contract name "AvaloniaVS.Services.IAvaloniaVSSettings" but found 0 after applying applicable constraints.
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "AvaloniaVS.Services.IAvaloniaVSSettings" but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(String contractName, ImportCardinality cardinality, Type type, Type metadataViewType, IMetadataViewProvider&amp; metadataViewProvider)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at AvaloniaVS.ServiceProviderExtensions.GetMefService[T](IServiceProvider sp) in D:\a\1\s\AvaloniaVS\ServiceProviderExtensions.cs:line 28
   at AvaloniaVS.AvaloniaPackage.InitializeLogging() in D:\a\1\s\AvaloniaVS\AvaloniaPackage.cs:line 0
   at AvaloniaVS.AvaloniaPackage.<InitializeAsync>d__6.MoveNext() in D:\a\1\s\AvaloniaVS\AvaloniaPackage.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
```
   
   
![image](https://user-images.githubusercontent.com/54960318/141074723-8d707d3b-df48-4c56-8420-6c58ff4720f6.png)

**Comment by adsgray70** [comment]
I have the same issue.  Have tried many workarounds but no luck. I did you find a solution.
