### ISSUE TITLE
XAML Autocomplete and Previewer does not work

### ISSUE THREAD

**Issue by alessandrofrancesconi** [AvaloniaUI/AvaloniaVS#430]
### Describe the bug

I'm working on a Avalonia 11 multiplatform project, for Android and iOS. Suddenly, the XAML editor does not provide autocompletion/IntelliSense anymore (CTRL+Space does not show anything), and the preview box is always empty:

![image](https://github.com/AvaloniaUI/AvaloniaVS/assets/1595223/b2fededc-b5d2-41f5-a099-8e8b23b88ddc)

The project compiles fine, tested with both -.NET 7 and .NET 8. 

Other projects I had using the same Avalonia version, works. How can I collect the necessary information to have a comprehensive view of what's broken, and debug?

### To Reproduce

I did not found a way to reproduce on another PC. 

### AvaloniaVS plugin version

11.5

### Avalonia version

11.0.6

### Visual Studio version

17.8.3

### Relevant log output

```shell
Avalonia Diagnostics tab is empty
```

**Comment by jonasnordlund** [comment]
I'm a new user of Avalonia + AvaloniaVS and same here. I first used Avalonia 11.0.6 as it was the latest release, then downgraded Avalonia to 11.0.4 as it was said this extension didn't yet support 11.0.6.

However, I still have this problem. Additionally, I get this stack trace when opening the axaml file.

```
12:00:26.630 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at VSLangProj.Reference.get_SourceProject()
   at AvaloniaVS.Services.SolutionService.<>c.<GetReferences>b__8_0(Reference x) in D:\a\1\s\AvaloniaVS.Shared\Services\SolutionService.cs:line 199
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AvaloniaVS.Services.SolutionService.<GetProjectsAsync>d__2.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Services\SolutionService.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAsync>d__55.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Views\AvaloniaDesigner.xaml.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAndStartProcessAsync>d__54.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Views\AvaloniaDesigner.xaml.cs:line 322
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at VSLangProj.Reference.get_SourceProject()
   at AvaloniaVS.Services.SolutionService.<>c.<GetReferences>b__8_0(Reference x) in D:\a\1\s\AvaloniaVS.Shared\Services\SolutionService.cs:line 199
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AvaloniaVS.Services.SolutionService.<GetProjectsAsync>d__2.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Services\SolutionService.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAsync>d__55.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Views\AvaloniaDesigner.xaml.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAndStartProcessAsync>d__54.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Views\AvaloniaDesigner.xaml.cs:line 322<---
```

**Comment by mrlacey** [comment]
Version 12.1 of the extension was released today and includes numerous improvements and fixes related to the displaying of UI previews.
I know this issue has been open for a long time, and thank you for your patience while we work to improve this.

We are still working to address the issue with Native AOT support, the problems when referencing C++ projects was also addressed previously.

**Comment by maxkatz6** [comment]
C++, PublishAot issues were previously fixed. And previewer is more informative now, when it fails with any error.
Closing this issue as solved, but please let us know if you still have issues.
