### ISSUE TITLE
Error creating XAML completion metadata

### ISSUE THREAD

**Issue by Wyvernius** [AvaloniaUI/AvaloniaVS#490]
### Describe the bug

Today i updated to Avalonia 11.1 and Net8.0.

And this message popped up.
Previewing Xamls works fine, but autocomplete is broken.

What i think is causing it is is that its looking for 'references' in the /obj folder.
But when i go to that folder there is no references file:

![Screenshot 2024-07-23 171529](https://github.com/user-attachments/assets/1b19e3c7-f29e-4247-bca7-c16670431463)

```
17:04:26.867 [Information]  Started AvaloniaDesigner.CreateCompletionMetadataAsync() for "E:\Slidecrew_Developments\V2\Slidecrew_V2_Avalonia\Win\Slidecrew\obj\Debug\net8.0-windows\win-x64\Avalonia\references"
17:04:26.867 [Error]  Error creating XAML completion metadata
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Avalonia.Ide.CompletionEngine.MetadataConverter.ConvertMetadata(IMetadataReaderSession provider)
   at Avalonia.Ide.CompletionEngine.AssemblyMetadata.MetadataReader.GetForTargetAssembly(IAssemblyProvider assemblyProvider)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<CreateCompletionMetadataAsync>d__64.MoveNext() in D:\a\1\s\AvaloniaVS.Shared\Views\AvaloniaDesigner.xaml.cs:line 609
```

I'm working in Visual Studio 2022.

### To Reproduce

Not sure.

### Avalonia version

11.1

### OS

Windows

**Comment by maxkatz6** [comment]
Fixed in 11.7.
