### ISSUE TITLE
i set design width 10500 by mistake .. visual studio freezed, had  to kill restart

### ISSUE THREAD

**Issue by blackholeearth** [AvaloniaUI/AvaloniaVS#505]
### Describe the bug

i set design width 10000 by mistake .. visual studio freezed,  cant do anything.

had  to kill vs , restart it

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" 
       d:DesignWidth="500" 
       d:DesignHeight="25600"
        x:Class="avaNetApp_TargetDesktop.MainWindow"
        Title="avaNetApp_TargetDesktop">

		
	<StackPanel>
		<Label> Stackpanel -> label1</Label>
		<DataGrid	Name="grid1">		</DataGrid>
				
		<Button Width="300" Height="30">label1</Button>
		<Button Width="300" Height="30">label3</Button>
		<WrapPanel>
			<Label> WrapPanel -> label1</Label>
		</WrapPanel>
		<Canvas>
			<Label> canvas -> label1</Label>
		</Canvas>
	</StackPanel>



</Window>


```

### To Reproduce

paste this code .
height to 1500
set desginwidth to  10000  or more ( 199000) 

**Solution:**
 it should time out after 5 seconds.    - preview timed out - coundt preview  im 5 seconds . 

OR

limit  previewer's max allowed preview size to 4000x4000 or whatever safe value.  
 so designer will not  freeze visual studio forever.

### AvaloniaVS plugin version

11.8

### Avalonia version

11.21

### Visual Studio version

visual studio 2022 - Version 17.11.5

### Relevant log output

```shell
vs crashed . dont have it.
```

### Additional context

   <PackageReference Include="Avalonia" Version="11.2.1" />
   <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.1" />
   <PackageReference Include="Avalonia.Desktop" Version="11.2.1" />
   <PackageReference Include="Avalonia.Markup.Declarative" Version="11.1.3" />
   <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.1" />
   <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.1" />

**Comment by blackholeearth** [comment]
i have installed 11.10.6 

i set width 19500 . i  press ctrl+s . 
i set width 500.  i  press ctrl+s . 
i set width 19500 . i  press ctrl+s . 

it freezed  .  then crashed...

**Comment by mrlacey** [comment]
The issue **does** still repro. (I think I was getting confused with zoom levels previously.)

The `DesignHeight` (and/or `DesignWidth`) is creating a surface so large that it throws an exception that isn't being handled.


I have to make the size much larger than that specified in the OPs repro. 
This suggests it may be a memory-related issue. If that's the case, then the size of what can be handled may be machine-dependent.

I'm not sure if there is a limit that should be being imposed on the size that it will attempt to render, or if should just try and stop the crash.
Probably both.


Exception:

```ascii
System.Runtime.InteropServices.COMException
  HResult=0x88980406
  Message=UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
  Source=PresentationCore
  StackTrace:
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush() in System.Windows.Media.Composition\DUCE.cs:line 241
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet) in System.Windows.Interop\HwndTarget.cs:line 1402
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam) in System.Windows.Interop\HwndTarget.cs:line 1294
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam) in System.Windows.Interop\HwndTarget.cs:line 816
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in System.Windows.Interop\HwndSource.cs:line 1084
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by blackholeearth** [comment]
İt seems that

Fix is  added to  Avalonia 11.3.9
