### ISSUE TITLE
COMException: Unspecified error in VS2019 with 0.8.0

### ISSUE THREAD

**Issue by OronDF343** [AvaloniaUI/AvaloniaVS#90]
The designer no longer loads for me in VS2019 16.1.0 Preview 1.0 after updating to 0.8.0:
(paths to my files trimmed)

```
09:29:36.311 [Information]  Avalonia Package initialized
10:29:05.474 [Verbose]  Started EditorFactory.CreateEditorInstance("\Sage\Views\MainWindow.xaml")
10:29:05.476 [Verbose]  Started EditorFactory.GetTextBuffer("\Sage\Views\MainWindow.xaml")
10:29:05.481 [Verbose]  Finished EditorFactory.GetTextBuffer("\Sage\Views\MainWindow.xaml")
10:29:05.482 [Verbose]  Started EditorFactory.CreateEditorControl()
10:29:05.520 [Verbose]  Finished EditorFactory.CreateEditorControl()
10:29:05.522 [Verbose]  Finished EditorFactory.CreateEditorInstance("\Sage\Views\MainWindow.xaml")
10:29:05.524 [Verbose]  Started DesignerPane.Initialize()
10:29:05.556 [Verbose]  Started AvaloniaDesigner.Start()
10:29:05.561 [Verbose]  Started AvaloniaDesigner.LoadTargetsAndStartProcessAsync()
10:29:05.566 [Verbose]  Started AvaloniaDesigner.LoadTargetsAsync()
10:29:05.611 [Verbose]  Finished AvaloniaDesigner.Start()
10:29:05.611 [Verbose]  Finished DesignerPane.Initialize()
10:29:05.611 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at EnvDTE.Configuration.get_Properties()
   at AvaloniaVS.Services.SolutionService.<GetOutputInfoAsync>d__9.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Services.SolutionService.<GetProjectsAsync>d__3.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAsync>d__31.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAndStartProcessAsync>d__30.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 217
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at EnvDTE.Configuration.get_Properties()
   at AvaloniaVS.Services.SolutionService.<GetOutputInfoAsync>d__9.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Services.SolutionService.<GetProjectsAsync>d__3.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAsync>d__31.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAndStartProcessAsync>d__30.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 217<---
```

**Comment by grokys** [comment]
> Unspecified error

Helpful! Ok, looks like i need to try it on VS 2019 preview. Does it work for you on VS2019 stable? Could be a bug in the preview release.

**Comment by OronDF343** [comment]
Just installed and tested, release 16.0.2 is working correctly.

**Comment by OronDF343** [comment]
Update: Tested with preview 2.0, no change. However, I have noticed that the exception is more detailed on the first launch of the designer:

```
17:55:32.505 [Information]  Avalonia Package initialized
17:55:32.516 [Verbose]  Started EditorFactory.CreateEditorInstance("\Sage\Views\MainWindow.xaml")
17:55:32.518 [Verbose]  Started EditorFactory.GetTextBuffer("\Sage\Views\MainWindow.xaml")
17:55:32.541 [Verbose]  Finished EditorFactory.GetTextBuffer("\Sage\Views\MainWindow.xaml")
17:55:32.542 [Verbose]  Started EditorFactory.CreateEditorControl()
17:55:33.124 [Verbose]  Finished EditorFactory.CreateEditorControl()
17:55:33.128 [Verbose]  Finished EditorFactory.CreateEditorInstance("\Sage\Views\MainWindow.xaml")
17:55:33.131 [Verbose]  Started DesignerPane.Initialize()
17:55:33.153 [Verbose]  Started AvaloniaDesigner.Start()
17:55:33.155 [Verbose]  Started AvaloniaDesigner.LoadTargetsAndStartProcessAsync()
17:55:33.158 [Verbose]  Started AvaloniaDesigner.LoadTargetsAsync()
17:55:33.178 [Verbose]  Finished AvaloniaDesigner.Start()
17:55:33.178 [Verbose]  Finished DesignerPane.Initialize()
17:55:35.058 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: Type library exporter encountered an error while processing 'Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages.PropertyPage, Microsoft.VisualStudio.ProjectSystem.Managed.VS'. Error: Type library exporter encountered an error while processing 'Microsoft.VisualStudio.Shell.Interop.SVsSolutionObject, Microsoft.VisualStudio.Shell.Interop'. Error: Type 'SVsSolutionObject' and type 'SVsSolution' both have the same UUID.
   at EnvDTE.Configuration.get_Properties()
   at AvaloniaVS.Services.SolutionService.<GetOutputInfoAsync>d__9.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Services.SolutionService.<GetProjectsAsync>d__3.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAsync>d__31.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAndStartProcessAsync>d__30.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 217
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80131163): Type library exporter encountered an error while processing 'Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages.PropertyPage, Microsoft.VisualStudio.ProjectSystem.Managed.VS'. Error: Type library exporter encountered an error while processing 'Microsoft.VisualStudio.Shell.Interop.SVsSolutionObject, Microsoft.VisualStudio.Shell.Interop'. Error: Type 'SVsSolutionObject' and type 'SVsSolution' both have the same UUID.
   at EnvDTE.Configuration.get_Properties()
   at AvaloniaVS.Services.SolutionService.<GetOutputInfoAsync>d__9.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Services.SolutionService.<GetProjectsAsync>d__3.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\SolutionService.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAsync>d__31.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AvaloniaVS.Views.AvaloniaDesigner.<LoadTargetsAndStartProcessAsync>d__30.MoveNext() in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Views\AvaloniaDesigner.xaml.cs:line 217<---
```

Looking more and more like a VS preview bug, I guess?
